### ISSUE TITLE
Uncaught TypeError: Cannot read property 'emojiarea' of undefined at new EmojiPicker (emoji-picker.coffee:8)

### ISSUE THREAD

**Issue by jacobrossdev** [OneSignal/emoji-picker#114]
I'm not really sure why this is showing up in Chrome. Shouldn't I be getting an error from the .js file and not the coffee script?

**Comment by jacobrossdev** [comment]
I figured this out. I deleted the emoji-picker.js.map then I was able to debug the issue from the emoji-picker.js file. Chrome made me think that `$` was defined when it wasn't. Since I'm using Wordpress, I had to change all instances of `$ `to `jQuery`.

**Comment by MehbubRashid** [comment]
@jacobrossdev thanks..this solved the issue for me too.
