### ISSUE TITLE
No working at all

### ISSUE THREAD

**Issue by Vickytan1995** [OneSignal/emoji-picker#116]
I followed the instructions and i not even have a emoji icon in the textarea. 
Following is my output
![image](https://user-images.githubusercontent.com/42161518/43751056-dc727f34-9a2d-11e8-8ec1-c58117ac41f3.png)
Following is my coding
![image](https://user-images.githubusercontent.com/42161518/43751075-ef0f7ef8-9a2d-11e8-8555-55f65e06c1d9.png)

Did i missing any thing ? Any one can help me ?

**Comment by IvoFacundo** [comment]
i have the same error, any advice?
