### ISSUE TITLE
converting emoji unicode back to emojis

### ISSUE THREAD

**Issue by ruchiy48** [OneSignal/emoji-picker#12]
While retrieving the emojis from the local database, we get unicode of that particular emoji.How to convert that unicode back to emoji.

**Comment by libofeng** [comment]
Currently, I use another javascript lib: js-emoji. But the problem is, we need to load ~10M resource when use these 2 javascript lib in my web application.

**Comment by mayank6199** [comment]
while retrieving emojis from database. it shows black & white emojis. how can i display colored images in list.

**Comment by TimBest** [comment]
you should just be able to set input's value to the unicode emojis and the emoji picker will convert it. 
example:
`<input type="text" data-emojiable="true" value="😄">`

**Comment by dominicklee** [comment]
Alright guys, I had the same request and need. To convert the unicode versions back into the same images you see in the Picker, you can do:

`window.emojiPicker.appendUnicodeAsImageToElement($("#yourDivID"),"😃")`

Replace `yourDivID` with whatever the id of your element. You can also use getElementByID('yourDivID') instead.

Hope this helps someone!
