### ISSUE TITLE
Using emoji-picker disable existing onkeypress

### ISSUE THREAD

**Issue by basilaiman** [OneSignal/emoji-picker#128]
I have this function 
`
        function onMsgBoxKeyPress(e) {
            console.log(e);
            if (e.which == 13) {
                onSendClick();
                return false;
            }
            return true;
        }
`
And this div
`<textarea data-emojiable="true" id="msgBox" class="form-control" onkeypress="return onMsgBoxKeyPress(event);" placeholder="Type Your Message"></textarea>`

Adding data-emojiable disabled the onkeypress event. and the `console.log(e);` line doesn't log anything

**Comment by hugocvx** [comment]
Add this to EmojiArea_WYSIWYG function :
`
    if ($($textarea).attr('onkeydown')) {
      this.$editor.attr('onkeydown', $textarea.attr('onkeydown'));
    }
    if ($($textarea).attr('onkeypress')) {
      this.$editor.attr('onkeypress', $textarea.attr('onkeypress'));
    }
`
