### ISSUE TITLE
No open emoji picker on iOS device

### ISSUE THREAD

**Issue by VeeRHunter** [OneSignal/emoji-picker#152]
I was made my own emoji picker and then it is not open emoji part on iOS device.
Code is exactly same as current one, I am not sure why this happened

**Comment by bLeveque42** [comment]
If you look at the source code, it was deactivated by default on iOS.

The reason is most likely because the iOS keyboard already offers emojis.

If you want to modify this behavior and show the plugin on iOS, in emoji-picker.js comment this block:

```
if (isiOS) {
     return;
}
```

**Comment by VeeRHunter** [comment]
Okay, thanks. let me check
