### ISSUE TITLE
Emoji menu not visible for mobile screen

### ISSUE THREAD

**Issue by ArpanTanna** [OneSignal/emoji-picker#19]
For small screen, only 1st column is visible. 
In demo page horizontal scroll appear in body to show other rows. But for responsive site, horizontal scroll is disabled so we can't visible other columns.

Can you please look at this issue? 

Regards,
Arpan

![emoji-mobile-issue](https://cloud.githubusercontent.com/assets/6537811/13695023/d01aad4a-e780-11e5-91a9-7565e893ff1f.png)

**Comment by TimBest** [comment]
The menu positioning has been updated:

<img width="352" alt="screen shot 2017-04-03 at 12 01 38 am" src="https://cloud.githubusercontent.com/assets/5008461/24598552/c299c76c-1800-11e7-917b-33823a7d4112.png">
