### ISSUE TITLE
emoji-menu transform change when scroll (tetherjs modified?)

### ISSUE THREAD

**Issue by viiiprock** [OneSignal/emoji-picker#21]
1. Before scroll
   .emoji-menu 
   transform: translateX(993px) translateY(194px) translateZ(0px);  
2. After scroll 
   transform: translateX(880px) translateY(194px) translateZ(0px);
## Expect

this.tether = new Tether({
        element: '[data-id="' + this.id + '"][data-type="menu"]',
        target: '[data-id="' + this.id + '"][data-type="picker"]',
        attachment: 'bottom center',
        targetAttachment: 'top center',
        offset: '230px 110px',   --------> **could change offset and make sense** 
          constraints: [
          {
            to: 'html',
            pin: true
          }
        ]
      });

**Comment by TimBest** [comment]
Tether is no longer a dependency of this project

**Comment by viiiprock** [comment]
Nice @TimBest
