### ISSUE TITLE
 emoji selector is not showing in my input even after including all the files 

### ISSUE THREAD

**Issue by rishav37** [OneSignal/emoji-picker#26]

**Comment by lucasfalanga** [comment]
Hello!

Did you make it work?
I'm having the same issue.

Thanks!

**Comment by marcosmfjunior** [comment]
+1

**Comment by MikeMoralesDEV** [comment]
The same here.

**Comment by dawidof** [comment]
+1

**Comment by dawidof** [comment]
without function like this

> // Initializes and creates emoji set from sprite sheet
      window.emojiPicker = new EmojiPicker({
        emojiable_selector: '[data-emojiable=true]',
        assetsPath: 'lib/img/',
        popupButtonClasses: 'fa fa-smile-o'
      });
      // Finds all elements with `emojiable_selector` and converts them to rich emoji input fields
      // You may want to delay this step if you have dynamically created input fields that appear later in the loading process
      // It can be called as many times as necessary; previously converted input fields will not be converted again
      window.emojiPicker.discover();

works for me

**Comment by aditya748** [comment]
@dawidof  Idk why this is not mentioned in docs. It worked for me (y)

**Comment by Tauka** [comment]
@rishav37 @lucasfalanga @marcosmfjunior Also include font-awesome css, worked for me

**Comment by noushad-pp** [comment]
included all files. added emojipicker.discover(). still not working.
versions:
"angular": "^1.4.0",

**Comment by TimBest** [comment]
So there is currently no default emoji selector one must be added using the `popupButtonClasses`. In the demo we use [font awesome](http://fontawesome.io/) to add the selector.

**Comment by anudeepjusanu** [comment]
Is this working with angular???

**Comment by noushad-pp** [comment]
@anudeepjusanu  yes it is. but you have to include the files yourself and initialise the emojipicker

**Comment by Andeson25** [comment]
@noushad-pp i added all files in angular cli , still not working
