### ISSUE TITLE
Emoji menu not visible for iPad

### ISSUE THREAD

**Issue by gozo77** [OneSignal/emoji-picker#36]
Can I use emoji-picker also for IPad? 
Because emoji icon and div were not generated.

![emoji-picker-ipad](https://cloud.githubusercontent.com/assets/20302901/16589778/d7f7b13e-42d4-11e6-845a-156d829f71a8.jpg)

**Comment by CanNuhlar** [comment]
See #49

**Comment by TimBest** [comment]
Fixed
