### ISSUE TITLE
How to save emoji in mysql and retrieve them perfect ? 

### ISSUE THREAD

**Issue by planetwebsolution** [OneSignal/emoji-picker#42]
I am saving unicode of emoji in db. It worked but when I retrieve, it did not work as expected. I can decode from unicode to emoji, it showed normal black and white emojis. I need the emoji image from spritesheet. Any help ?

**Comment by aminin** [comment]
Hi, @planetwebsolution !

MySQL issues are beyound the scope of this project. Though [LMGTFU](http://lmgtfy.com/?q=How+to+use+full+unicode+in+mysql&l=1).

**Comment by planetwebsolution** [comment]
@aminin Okay but when I choose `element.val()` I get the unicode value of emoji. That's right but is there anyway to get emoji back from unicode ?

**Comment by aminin** [comment]
@planetwebsolution, try [emojione](http://git.emojione.com/demos/latest/phpunicodetoimage.php)

**Comment by mayank6199** [comment]
colored emojis not supported in google chrome 54.0.2840.99

**Comment by mayank6199** [comment]
when i insert emojis as input like this:
![emoji input](https://cloud.githubusercontent.com/assets/20205221/20521702/8173ec62-b0d2-11e6-908c-d3d45595345a.png)

and when retrieve it from database it changes :+1:  
![emoji output](https://cloud.githubusercontent.com/assets/20205221/20521704/88951250-b0d2-11e6-84ce-4d4d9e5e5dab.png)

anyone have solution for it?

**Comment by raduca-adrian** [comment]
Hi,

Creating a column as indicated in #51 seems to work for me. Also having the ```data-emoji-input="unicode"``` on the input.

**Comment by TimBest** [comment]
out of scope

**Comment by dominicklee** [comment]
> @aminin Okay but when I choose `element.val()` I get the unicode value of emoji. That's right but is there anyway to get emoji back from unicode ?

Alright guys, I had the same request and need. To convert the unicode versions back into the same images you see in the Picker, you can do:

`window.emojiPicker.appendUnicodeAsImageToElement($("#yourDivID"),"😃")`

Replace `yourDivID` with whatever the id of your element. You can also use getElementByID('yourDivID') instead.

Hope this helps someone!
