### ISSUE TITLE
Works on every device except for safari on iPhone or iPad

### ISSUE THREAD

**Issue by KBepo** [OneSignal/emoji-picker#49]
Even if you open demo page it doesn't work.

**Comment by CanNuhlar** [comment]
Easy fix, just comment out line 21, 22 and 23. But you should tweak the css to make emoji window place correctly. If this project is not dead I would like to fix this. 

` EmojiPicker.prototype.discover = function() {
      var isiOS;
      isiOS = /iPad|iPhone|iPod/.test(navigator.userAgent) && !window.MSStream;
//      if (isiOS) {
//        return;
//      }
      return $(this.options.emojiable_selector).emojiarea($.extend({
        emojiPopup: this,
        norealTime: true
      }, this.options));
    };`

**Comment by TimBest** [comment]
Fixed
