### ISSUE TITLE
Can't install via bower, needs master branch

### ISSUE THREAD

**Issue by pstreck** [OneSignal/emoji-picker#52]
Can you create a master branch so this is installable via bower? The error I get when trying to install is:

bower not-cached    https://github.com/OneSignal/emoji-picker.git#*
bower resolve       https://github.com/OneSignal/emoji-picker.git#*
bower ENORESTARGET  Tag/branch master does not exist

Additional error details:
Available tags: 1.0
Available branches: gh-pages

**Comment by TimBest** [comment]
added master branch
