### ISSUE TITLE
jQuery on('keyup') didn't working

### ISSUE THREAD

**Issue by RafaelPlantard** [OneSignal/emoji-picker#53]
After using `data-emoji-input="unicode" data-emojiable="true"` all `keyup` binding data stop to working. Just working with `change` event.

**Comment by mhetreramesh** [comment]
I'm also facing the same issue? Does someone looking into it?

**Comment by ThPadelis** [comment]
I got the same problem too, but I can log out which key is pressed. My problem is that I can't submit the form on enter (e.which == 13).

**Comment by Fabiombrs** [comment]
ThPadelis Managed to solve?

**Comment by ThPadelis** [comment]
@Fabiombrs still can't figure out what's wrong...

**Comment by Fabiombrs** [comment]
@ThPadelis Did you test someone else?
would have some to indicate?
thankful !

**Comment by leeadh** [comment]
HI hi, this didnt work. I tried to use this and placed in jquery.emojiarea.js but no luck :(

**Comment by anaconda0905** [comment]
After using data-emojiable="true" all keydown binding data stop to working. When I type the key 'enter', the messages must be submitted. However, after using emoji-picker, it doesn't work properly, Thanks in advance. Please help me.

**Comment by jscouvert** [comment]
Here is trhe solution. Use norealTime parameter (set to false)  : 

Like this : 
```
new EmojiPicker({
                                emojiable_selector: ".hasEmojiPicker.picker_" + translatekey_field,
                                assetsPath: "/js/plugins/emoji-picker/img/",
                                popupButtonClasses: "fa fa-smile-o input-group-btn btn btn-default",
                                norealTime: false
                            });`
```
