### ISSUE TITLE
New Line in Text Area

### ISSUE THREAD

**Issue by karopass** [OneSignal/emoji-picker#75]
Hi ! I does not need single line in textarea. I am trying to add new line via Enter key...in Text Area its showing new line but when it got saved in database...its come in single line.. How can I solve that issue ?
Thanks

**Comment by carlesAlterego** [comment]
I'm getting same issue, did you find any way to do it?

**Comment by rziw** [comment]
I have the same problem :| no one find any way?

**Comment by Ricardo-Costa** [comment]
me2
