### ISSUE TITLE
Emoji icon is not showing.

### ISSUE THREAD

**Issue by gullocean** [OneSignal/emoji-picker#91]
I am very interested in this plugin, but this doesn't work on my website.
<textarea rows="8" class="form-control resizebox" name="pval[description]" id="description1" placeholder="Enter text here" required data-emojiable="true"></textarea>

I already include jQuery, js and css files which is needed for this plugin, but it doesn't work.
Maybe is there any special method which I can miss for this plugin?

**Comment by cduran433** [comment]
I think that you forget to add the call to init the plugin:

`            window.emojiPicker = new EmojiPicker({
                assetsPath: 'lib/images/',
                popupButtonClasses: 'fa fa-smile-o'
            });
            window.emojiPicker.discover();`

**Comment by gullocean** [comment]
@cduran433  Thanks for your help. It works good. Awesome. (Finger Crossed)
